services:
  postgres:
    container_name: blog_postgres_db
    image: 'postgres:16.0'
    environment:
        POSTGRES_USER: 'admin'
        POSTGRES_PASSWORD: 'admin'
        POSTGRES_DB: 'payment_db'
      
    ports:
        - '5432:5432'