global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  # scape data from direct prometheus exporter of spring boot application payment service
  - job_name: 'scrape-payment-service-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  # scrape data from the prometheus exporter of the otel-collector
  - job_name: 'scrape-otel-collector-job'
    static_configs:
      - targets: ['otel-collector:8889']
